### ISSUE TITLE
'Failed to set/get viewport size' error in Mobile Android Browser

### ISSUE THREAD

**Issue by klamping** [applitools/eyes.webdriverio.javascript#16]
When trying to run `checkWindow` in Mobile Android, I'm getting the following error:
```
Failed to set/get viewport size: The URL '/wd/hub/session/XXXXXXXX-XXXX-XXXX-XXXX-XXXX29b676bc/window/rect' did not map to a valid resource
running Chrome
Error: The URL '/wd/hub/session/XXXXXXXX-XXXX-XXXX-XXXX-XXXX29b676bc/window/rect' did not map to a valid resource
    at pause(200) - index.js:267:37
    at execute("var origOverflow = document.documentElement.style.overflow; document.documentElement.style.overflow = "hidden"; return origOverflow", ) - index.js:267:37
    at elements() - isExisting.js:46:17
    at isExisting() - at windowHandleSize() - index.js:267:37
```

My capabilities:
```
{
  browserName: 'Chrome',
  deviceName: 'Android Emulator',
  deviceOrientation: 'portrait',
  platformVersion: '6.0',
  platformName: 'Android',
},
```

From a quick investigation, [it looks like Applitools is trying to get the browser size](https://github.com/applitools/eyes.webdriverio.javascript/blob/d46f9e5f2eec2d149b991c70ab47f035f6109a35/src/EyesWDIOUtils.js#L462) via `windowHandleSize`, but Android (and maybe all mobile browsers?) don't support that endpoint. 

I'm guessing a conditional will need to be added to only check for windowHandleSize if it's not a mobile browser.

**Comment by danielputerman** [comment]
Fixed in https://github.com/applitools/eyes.webdriverio.javascript/pull/14, and available in npm since version 1.1.1 .
