### ISSUE TITLE
Unable to use applitools with CodeceptJS

### ISSUE THREAD

**Issue by jordiponsllaurado** [applitools/eyes.webdriverio.javascript#44]
It seems like CodeceptJS use webdriverIO v5 and Applitools uses v4.12 since v5 changed the API this makes not possible to execute tests on CodeceptJS.

CodeceptJS issue: https://github.com/Codeception/CodeceptJS/issues/1488

It could be solved merging this PR https://github.com/applitools/eyes.webdriverio.javascript/pull/19

**Comment by yuriieasternpeak** [comment]
@jordiponsllaurado 
now we have new version with wdio v5 support - https://www.npmjs.com/package/@applitools/eyes-webdriverio
